Toolbox: toolbox::util::OStaticStream< MaxN > Class Template Reference
toolbox::util::OStaticStream< MaxN > Class Template Reference final
#include <toolbox/util/Stream.hpp>
Public Member Functions
OStaticStream ()=default
~OStaticStream ()=default
OStaticStream (const OStaticStream &)=delete
OStaticStream & operator= (const OStaticStream &)=delete
OStaticStream (OStaticStream &&)=delete
OStaticStream & operator= (OStaticStream &&)=delete
const char * data () const noexcept
bool empty () const noexcept
std::size_t size () const noexcept
std::string_view str () const noexcept
operator bool () const
void reset () noexcept
Reset the current position back to the beginning of the buffer.
Public Member Functions inherited from toolbox::util::OStreamBase< OStaticStream< MaxN > >
OStaticStream< MaxN > & put_data (const char *data, std::size_t data_size)
OStaticStream< MaxN > & put_char (T ch)
OStaticStream< MaxN > & put_num (bool val)
OStaticStream< MaxN > & put_num (T val)
OStaticStream< MaxN > & put_num (T val)
OStaticStream< MaxN > & put (char ch)
For compatability with std::ostream API.
OStaticStream< MaxN > & write (const char *data, std::size_t sz)
OStaticStream< MaxN > & put_data (const char *data, std::size_t data_size)
OStaticStream< MaxN > & put_char (T ch)
OStaticStream< MaxN > & put_num (bool val)
OStaticStream< MaxN > & put_num (T val)
OStaticStream< MaxN > & put_num (T val)
OStaticStream< MaxN > & put (char ch)
For compatability with std::ostream API.
OStaticStream< MaxN > & write (const char *data, std::size_t sz)
Additional Inherited Members
Static Protected Attributes inherited from toolbox::util::OStreamBase< OStaticStream< MaxN > >
static constexpr std::size_t PutNumMaxBufRequest
static constexpr std::size_t PutNumMaxBufRequest
Detailed Description
template<std::size_t MaxN>
class toolbox::util::OStaticStream< MaxN >
Definition at line 147 of file Stream.hpp.
Constructor & Destructor Documentation
OStaticStream() [1/3]
template<std::size_t MaxN> toolbox::util::OStaticStream< MaxN >::OStaticStream () default
~OStaticStream()
template<std::size_t MaxN> toolbox::util::OStaticStream< MaxN >::~OStaticStream () default
OStaticStream() [2/3]
template<std::size_t MaxN> toolbox::util::OStaticStream< MaxN >::OStaticStream (const OStaticStream< MaxN > &) delete
OStaticStream() [3/3]
template<std::size_t MaxN> toolbox::util::OStaticStream< MaxN >::OStaticStream (OStaticStream< MaxN > &&) delete
Member Function Documentation
operator=() [1/2]
template<std::size_t MaxN> OStaticStream & toolbox::util::OStaticStream< MaxN >::operator= (const OStaticStream< MaxN > &) delete
operator=() [2/2]
template<std::size_t MaxN> OStaticStream & toolbox::util::OStaticStream< MaxN >::operator= (OStaticStream< MaxN > &&) delete
data()
template<std::size_t MaxN> const char * toolbox::util::OStaticStream< MaxN >::data () const inline noexcept
Definition at line 160 of file Stream.hpp.
empty()
template<std::size_t MaxN> bool toolbox::util::OStaticStream< MaxN >::empty () const inline noexcept
Definition at line 161 of file Stream.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
size()
template<std::size_t MaxN> std::size_t toolbox::util::OStaticStream< MaxN >::size () const inline noexcept
Definition at line 162 of file Stream.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), and toolbox::util::OStaticStream< MaxN >::str().
str()
template<std::size_t MaxN> std::string_view toolbox::util::OStaticStream< MaxN >::str () const inline noexcept
Definition at line 163 of file Stream.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), and toolbox::util::ErrMsg::operator std::string_view().
operator bool()
template<std::size_t MaxN> toolbox::util::OStaticStream< MaxN >::operator bool () const inline explicit
Definition at line 167 of file Stream.hpp.
reset()
template<std::size_t MaxN> void toolbox::util::OStaticStream< MaxN >::reset () inline noexcept
Reset the current position back to the beginning of the buffer.
Definition at line 172 of file Stream.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
The documentation for this class was generated from the following file:
toolbox/util/Stream.hpp