Toolbox: toolbox::hdr::HdrHistogram Class Reference
toolbox::hdr::HdrHistogram Class Reference
A High Dynamic Range (HDR) Histogram.
#include <toolbox/hdr/Histogram.hpp>
Public Member Functions
HdrHistogram (const HdrBucketConfig &config)
HdrHistogram (std::int64_t lowest_trackable_value, std::int64_t highest_trackable_value, std::int32_t significant_figures)
HdrHistogram (const HdrHistogram &)=default
HdrHistogram & operator= (const HdrHistogram &)=default
HdrHistogram (HdrHistogram &&) noexcept=default
HdrHistogram & operator= (HdrHistogram &&) noexcept=default
std::int64_t lowest_trackable_value () const noexcept
std::int64_t highest_trackable_value () const noexcept
std::int32_t significant_figures () const noexcept
std::int32_t sub_bucket_count () const noexcept
std::int32_t bucket_count () const noexcept
std::int64_t total_count () const noexcept
std::int32_t counts_len () const noexcept
std::int64_t min () const noexcept
Get minimum value from the histogram. Will return 2^63-1 if the histogram is empty.
std::int64_t max () const noexcept
Get maximum value from the histogram. Will return 0 if the histogram is empty.
bool values_are_equivalent (std::int64_t a, std::int64_t b) const noexcept
std::int64_t lowest_equivalent_value (std::int64_t value) const noexcept
std::int64_t highest_equivalent_value (std::int64_t value) const noexcept
std::int64_t count_at_value (std::int64_t value) const noexcept
std::int64_t count_at_index (std::int32_t index) const noexcept
std::int64_t value_at_index (std::int32_t index) const noexcept
std::int64_t size_of_equivalent_value_range (std::int64_t value) const noexcept
std::int64_t next_non_equivalent_value (std::int64_t value) const noexcept
std::int64_t median_equivalent_value (std::int64_t value) const noexcept
std::int64_t counts_get_normalised (std::int32_t index) const noexcept
void reset () noexcept
bool record_value (std::int64_t value) noexcept
bool record_values (std::int64_t value, std::int64_t count) noexcept
Detailed Description
A High Dynamic Range (HDR) Histogram.
Definition at line 63 of file Histogram.hpp.
Constructor & Destructor Documentation
HdrHistogram() [1/4]
toolbox::hdr::HdrHistogram::HdrHistogram (const HdrBucketConfig & config)
Definition at line 96 of file Histogram.cpp.
HdrHistogram() [2/4]
toolbox::hdr::HdrHistogram::HdrHistogram (std::int64_t lowest_trackable_value, std::int64_t highest_trackable_value, std::int32_t significant_figures)
HdrHistogram() [3/4]
toolbox::hdr::HdrHistogram::HdrHistogram (const HdrHistogram &) default
HdrHistogram() [4/4]
toolbox::hdr::HdrHistogram::HdrHistogram (HdrHistogram &&) default noexcept
Member Function Documentation
operator=() [1/2]
HdrHistogram& toolbox::hdr::HdrHistogram::operator= (const HdrHistogram &) default
operator=() [2/2]
HdrHistogram& toolbox::hdr::HdrHistogram::operator= (HdrHistogram &&) default noexcept
lowest_trackable_value()
std::int64_t toolbox::hdr::HdrHistogram::lowest_trackable_value () const inline noexcept
Definition at line 77 of file Histogram.hpp.
Referenced by HdrHistogram().
highest_trackable_value()
std::int64_t toolbox::hdr::HdrHistogram::highest_trackable_value () const inline noexcept
Definition at line 78 of file Histogram.hpp.
Referenced by HdrHistogram().
significant_figures()
std::int32_t toolbox::hdr::HdrHistogram::significant_figures () const inline noexcept
Definition at line 79 of file Histogram.hpp.
Referenced by HdrHistogram(), and toolbox::hdr::operator<<().
sub_bucket_count()
std::int32_t toolbox::hdr::HdrHistogram::sub_bucket_count () const inline noexcept
Definition at line 81 of file Histogram.hpp.
Referenced by toolbox::hdr::operator<<().
bucket_count()
std::int32_t toolbox::hdr::HdrHistogram::bucket_count () const inline noexcept
Definition at line 82 of file Histogram.hpp.
Referenced by toolbox::hdr::operator<<().
total_count()
std::int64_t toolbox::hdr::HdrHistogram::total_count () const inline noexcept
Definition at line 83 of file Histogram.hpp.
Referenced by toolbox::hdr::operator<<().
counts_len()
std::int32_t toolbox::hdr::HdrHistogram::counts_len () const inline noexcept
Definition at line 84 of file Histogram.hpp.
Referenced by record_values().
min()
int64_t toolbox::hdr::HdrHistogram::min () const noexcept
Get minimum value from the histogram. Will return 2^63-1 if the histogram is empty.
Definition at line 121 of file Histogram.cpp.
max()
int64_t toolbox::hdr::HdrHistogram::max () const noexcept
Get maximum value from the histogram. Will return 0 if the histogram is empty.
Definition at line 129 of file Histogram.cpp.
Referenced by toolbox::hdr::operator<<().
values_are_equivalent()
bool toolbox::hdr::HdrHistogram::values_are_equivalent (std::int64_t a, std::int64_t b) const noexcept
Determine if two values are equivalent with the histogram's resolution. Where "equivalent" means that value samples recorded for any two equivalent values are counted in a common total count.
Parameters
a first value to compare.
b second value to compare.
Returns
true if values are equivalent with the histogram's resolution.
Definition at line 137 of file Histogram.cpp.
lowest_equivalent_value()
int64_t toolbox::hdr::HdrHistogram::lowest_equivalent_value (std::int64_t value) const noexcept
Get the lowest value that is equivalent to the given value within the histogram's resolution. Where "equivalent" means that value samples recorded for any two equivalent values are counted in a common total count.
Parameters
value The given value.
Returns
the lowest value that is equivalent to the given value within the histogram's resolution.
Definition at line 142 of file Histogram.cpp.
Referenced by toolbox::hdr::HdrRecordedIterator::do_next(), toolbox::hdr::HdrLinearIterator::do_next(), toolbox::hdr::HdrLogIterator::do_next(), median_equivalent_value(), next_non_equivalent_value(), record_values(), and values_are_equivalent().
highest_equivalent_value()
int64_t toolbox::hdr::HdrHistogram::highest_equivalent_value (std::int64_t value) const noexcept
Definition at line 149 of file Histogram.cpp.
Referenced by max().
count_at_value()
int64_t toolbox::hdr::HdrHistogram::count_at_value (std::int64_t value) const noexcept
Get the count of recorded values at a specific value (to within the histogram resolution at the value level).
Parameters
value The value for which to provide the recorded count.
Returns
The total count of values recorded in the histogram within the value range.
Definition at line 154 of file Histogram.cpp.
count_at_index()
int64_t toolbox::hdr::HdrHistogram::count_at_index (std::int32_t index) const noexcept
Definition at line 159 of file Histogram.cpp.
Referenced by min().
value_at_index()
int64_t toolbox::hdr::HdrHistogram::value_at_index (std::int32_t index) const noexcept
Definition at line 164 of file Histogram.cpp.
size_of_equivalent_value_range()
int64_t toolbox::hdr::HdrHistogram::size_of_equivalent_value_range (std::int64_t value) const noexcept
Definition at line 176 of file Histogram.cpp.
Referenced by median_equivalent_value(), and next_non_equivalent_value().
next_non_equivalent_value()
int64_t toolbox::hdr::HdrHistogram::next_non_equivalent_value (std::int64_t value) const noexcept
Definition at line 185 of file Histogram.cpp.
Referenced by highest_equivalent_value().
median_equivalent_value()
int64_t toolbox::hdr::HdrHistogram::median_equivalent_value (std::int64_t value) const noexcept
Definition at line 190 of file Histogram.cpp.
counts_get_normalised()
int64_t toolbox::hdr::HdrHistogram::counts_get_normalised (std::int32_t index) const noexcept
Definition at line 195 of file Histogram.cpp.
Referenced by count_at_index(), and count_at_value().
reset()
void toolbox::hdr::HdrHistogram::reset () noexcept
Reset a histogram to zero - empty out a histogram and re-initialise it.
If you want to re-use an existing histogram, but reset everything back to zero, this is the routine to use.
Definition at line 200 of file Histogram.cpp.
record_value()
bool toolbox::hdr::HdrHistogram::record_value (std::int64_t value) noexcept
Records a value in the histogram, will round this value of to a precision at or better than the significant_figure specified at construction time.
Parameters
value Value to add to the histogram.
Returns
false if the value is larger than the highest_trackable_value and can't be recorded, true otherwise.
Definition at line 208 of file Histogram.cpp.
record_values()
bool toolbox::hdr::HdrHistogram::record_values (std::int64_t value, std::int64_t count) noexcept
Records count values in the histogram, will round this value of to a precision at or better than the significant_figure specified at construction time.
Parameters
value Value to add to the histogram.
count Number of values to add to the histogram.
Returns
false if any value is larger than the highest_trackable_value and can't be recorded, true otherwise.
Definition at line 213 of file Histogram.cpp.
Referenced by record_value().
The documentation for this class was generated from the following files:
toolbox/hdr/Histogram.hpp
toolbox/hdr/Histogram.cpp