Toolbox: toolbox::util::OStreamBase< DerivedT > Class Template Reference
toolbox::util::OStreamBase< DerivedT > Class Template Reference
#include <toolbox/util/OStreamBase.hpp>
Public Member Functions
DerivedT & put_data (const char *data, std::size_t data_size) noexcept
template<class T >
requires detail::AllowedChar<T>
DerivedT & put_char (T ch) noexcept
DerivedT & put_num (bool val) noexcept
template<class T >
requires (detail::AllowedIntegral<T> && !std::same_as<T, bool>)
DerivedT & put_num (T val) noexcept
template<class T >
requires std::floating_point<T>
DerivedT & put_num (T val) noexcept
DerivedT & put (char ch) noexcept
For compatability with std::ostream API.
DerivedT & write (const char *data, std::size_t sz) noexcept
Static Protected Attributes
static constexpr std::size_t PutNumMaxBufRequest = 32u
Detailed Description
template<class DerivedT>
class toolbox::util::OStreamBase< DerivedT >
Definition at line 73 of file OStreamBase.hpp.
Member Function Documentation
put_data()
template<class DerivedT > DerivedT & toolbox::util::OStreamBase< DerivedT >::put_data (const char * data, std::size_t data_size) noexcept
Definition at line 139 of file OStreamBase.hpp.
Referenced by toolbox::util::OStreamBase< DerivedT >::write().
put_char()
template<class DerivedT > requires detail::AllowedChar<T> template<class T > requires detail::AllowedChar<T> DerivedT & toolbox::util::OStreamBase< DerivedT >::put_char (T ch) noexcept
Definition at line 153 of file OStreamBase.hpp.
Referenced by toolbox::util::OStreamBase< DerivedT >::put(), and toolbox::util::OStreamBase< DerivedT >::put_num().
put_num() [1/3]
template<class DerivedT > DerivedT & toolbox::util::OStreamBase< DerivedT >::put_num (bool val) noexcept
Definition at line 166 of file OStreamBase.hpp.
put_num() [2/3]
template<class DerivedT > requires (detail::AllowedIntegral<T> && !std::same_as<T, bool>) template<class T > requires (detail::AllowedIntegral<T> && !std::same_as<T, bool>) DerivedT & toolbox::util::OStreamBase< DerivedT >::put_num (T val) noexcept
Definition at line 174 of file OStreamBase.hpp.
put_num() [3/3]
template<class DerivedT > template<class T > requires std::floating_point<T> DerivedT & toolbox::util::OStreamBase< DerivedT >::put_num (T val) noexcept
put()
template<class DerivedT > DerivedT & toolbox::util::OStreamBase< DerivedT >::put (char ch) noexcept
For compatability with std::ostream API.
Definition at line 240 of file OStreamBase.hpp.
write()
template<class DerivedT > DerivedT & toolbox::util::OStreamBase< DerivedT >::write (const char * data, std::size_t sz) noexcept
Definition at line 246 of file OStreamBase.hpp.
Member Data Documentation
PutNumMaxBufRequest
template<class DerivedT > constexpr std::size_t toolbox::util::OStreamBase< DerivedT >::PutNumMaxBufRequest = 32u static constexpr protected
Definition at line 101 of file OStreamBase.hpp.
Referenced by toolbox::util::OStreamBase< DerivedT >::put_num().
The documentation for this class was generated from the following file:
toolbox/util/OStreamBase.hpp