Toolbox: toolbox::util::benchmark::BenchmarkStore Class Reference
toolbox::util::benchmark::BenchmarkStore Class Reference
#include <toolbox/util/Benchmark.hpp>
Public Member Functions
void store (const char *name, Runnable &runnable)
void list () const
void run (const std::string &regex, bool randomise)
Static Public Member Functions
static BenchmarkStore & instance ()
Detailed Description
Definition at line 73 of file Benchmark.hpp.
Member Function Documentation
instance()
BenchmarkStore & toolbox::util::benchmark::BenchmarkStore::instance () static
Definition at line 28 of file Benchmark.cpp.
Referenced by toolbox::util::benchmark::Benchmark< FuncT >::Benchmark(), and toolbox::util::benchmark::detail::main().
store()
void toolbox::util::benchmark::BenchmarkStore::store (const char * name, Runnable & runnable)
Definition at line 34 of file Benchmark.cpp.
Referenced by toolbox::util::benchmark::Benchmark< FuncT >::Benchmark(), instance(), and toolbox::util::benchmark::detail::main().
list()
void toolbox::util::benchmark::BenchmarkStore::list () const
Definition at line 39 of file Benchmark.cpp.
Referenced by toolbox::util::benchmark::detail::main().
run()
void toolbox::util::benchmark::BenchmarkStore::run (const std::string & regex, bool randomise)
Definition at line 46 of file Benchmark.cpp.
The documentation for this class was generated from the following files:
toolbox/util/Benchmark.hpp
toolbox/util/Benchmark.cpp