Toolbox: toolbox::util::propagate_const< T > Class Template Reference
toolbox::util::propagate_const< T > Class Template Reference
#include <toolbox/util/PropagateConst.hpp>
Public Member Functions
propagate_const ()=default
~propagate_const ()=default
propagate_const (T obj)
propagate_const (propagate_const &o)=default
propagate_const & operator= (propagate_const &)=default
propagate_const (const propagate_const &)=delete
propagate_const & operator= (const propagate_const &)=delete
propagate_const (propagate_const &&)=default
propagate_const & operator= (propagate_const &&)=default
propagate_const & operator= (T &&other)
propagate_const & operator= (const T &other)
pointed_type * get ()
const pointed_type * get () const
pointed_type * operator-> ()
const pointed_type * operator-> () const
pointed_type & operator* ()
const pointed_type & operator* () const
operator pointed_type * ()
operator const pointed_type * () const
operator bool () const
Friends
bool operator== (const propagate_const &, const propagate_const &)=default
auto operator<=> (const propagate_const &, const propagate_const &)=default
template<class U >
auto operator<=> (const propagate_const &p, const U &o)
template<typename U >
auto operator== (const propagate_const &p, const U &o)
bool operator== (const propagate_const &p, std::nullptr_t)
void swap (propagate_const &a, propagate_const &b)
Detailed Description
template<class T>
class toolbox::util::propagate_const< T >
Definition at line 48 of file PropagateConst.hpp.
Constructor & Destructor Documentation
propagate_const() [1/5]
template<class T > toolbox::util::propagate_const< T >::propagate_const () default
~propagate_const()
template<class T > toolbox::util::propagate_const< T >::~propagate_const () default
propagate_const() [2/5]
template<class T > toolbox::util::propagate_const< T >::propagate_const (T obj) inline explicit
Definition at line 57 of file PropagateConst.hpp.
propagate_const() [3/5]
template<class T > toolbox::util::propagate_const< T >::propagate_const (propagate_const< T > & o) default
propagate_const() [4/5]
template<class T > toolbox::util::propagate_const< T >::propagate_const (const propagate_const< T > &) delete
propagate_const() [5/5]
template<class T > toolbox::util::propagate_const< T >::propagate_const (propagate_const< T > &&) default
Member Function Documentation
operator=() [1/5]
template<class T > propagate_const & toolbox::util::propagate_const< T >::operator= (propagate_const< T > &) default
operator=() [2/5]
template<class T > propagate_const & toolbox::util::propagate_const< T >::operator= (const propagate_const< T > &) delete
operator=() [3/5]
template<class T > propagate_const & toolbox::util::propagate_const< T >::operator= (propagate_const< T > &&) default
operator=() [4/5]
template<class T > propagate_const & toolbox::util::propagate_const< T >::operator= (T && other) inline
Definition at line 71 of file PropagateConst.hpp.
operator=() [5/5]
template<class T > propagate_const & toolbox::util::propagate_const< T >::operator= (const T & other) inline
Definition at line 76 of file PropagateConst.hpp.
get() [1/2]
template<class T > pointed_type * toolbox::util::propagate_const< T >::get () inline
Definition at line 82 of file PropagateConst.hpp.
Referenced by toolbox::util::propagate_const< T >::operator bool(), toolbox::util::propagate_const< T >::operator const pointed_type *(), toolbox::util::propagate_const< T >::operator pointed_type *(), toolbox::util::propagate_const< T >::operator*(), toolbox::util::propagate_const< T >::operator*(), toolbox::util::propagate_const< T >::operator->(), and toolbox::util::propagate_const< T >::operator->().
get() [2/2]
template<class T > const pointed_type * toolbox::util::propagate_const< T >::get () const inline
Definition at line 83 of file PropagateConst.hpp.
operator->() [1/2]
template<class T > pointed_type * toolbox::util::propagate_const< T >::operator-> () inline
Definition at line 85 of file PropagateConst.hpp.
operator->() [2/2]
template<class T > const pointed_type * toolbox::util::propagate_const< T >::operator-> () const inline
Definition at line 86 of file PropagateConst.hpp.
operator*() [1/2]
template<class T > pointed_type & toolbox::util::propagate_const< T >::operator* () inline
Definition at line 88 of file PropagateConst.hpp.
operator*() [2/2]
template<class T > const pointed_type & toolbox::util::propagate_const< T >::operator* () const inline
Definition at line 89 of file PropagateConst.hpp.
operator pointed_type *()
template<class T > toolbox::util::propagate_const< T >::operator pointed_type * () inline
Definition at line 91 of file PropagateConst.hpp.
operator const pointed_type *()
template<class T > toolbox::util::propagate_const< T >::operator const pointed_type * () const inline
Definition at line 92 of file PropagateConst.hpp.
operator bool()
template<class T > toolbox::util::propagate_const< T >::operator bool () const inline explicit
Definition at line 94 of file PropagateConst.hpp.
Friends And Related Symbol Documentation
operator== [1/3]
template<class T > bool operator== (const propagate_const< T > & , const propagate_const< T > &) friend
operator<=> [1/2]
template<class T > auto operator<=> (const propagate_const< T > & , const propagate_const< T > &) friend
operator<=> [2/2]
template<class T > template<class U > auto operator<=> (const propagate_const< T > & p, const U & o) friend
Definition at line 100 of file PropagateConst.hpp.
operator== [2/3]
template<class T > template<typename U > auto operator== (const propagate_const< T > & p, const U & o) friend
Definition at line 105 of file PropagateConst.hpp.
operator== [3/3]
template<class T > bool operator== (const propagate_const< T > & p, std::nullptr_t) friend
Definition at line 110 of file PropagateConst.hpp.
swap
template<class T > void swap (propagate_const< T > & a, propagate_const< T > & b) friend
Definition at line 112 of file PropagateConst.hpp.
The documentation for this class was generated from the following file:
toolbox/util/PropagateConst.hpp