Toolbox: toolbox::util::StringBuf< MaxN > Class Template Reference
toolbox::util::StringBuf< MaxN > Class Template Reference
String buffer with fixed upper-bound.
#include <toolbox/util/StringBuf.hpp>
Public Member Functions
template<std::size_t MaxR>
StringBuf (const StringBuf< MaxR > &rhs) noexcept
StringBuf (std::string_view rhs) noexcept
constexpr StringBuf () noexcept=default
~StringBuf ()=default
StringBuf (const StringBuf &rhs) noexcept
StringBuf & operator= (const StringBuf &rhs) noexcept
constexpr StringBuf (StringBuf &&) noexcept=default
constexpr StringBuf & operator= (StringBuf &&) noexcept=default
template<std::size_t MaxR>
StringBuf & operator= (const StringBuf< MaxR > &rhs) noexcept
StringBuf & operator= (std::string_view rhs) noexcept
template<std::size_t MaxR>
StringBuf & operator+= (const StringBuf< MaxR > &rhs) noexcept
StringBuf & operator+= (std::string_view rhs) noexcept
constexpr const char * data () const noexcept
constexpr bool empty () const noexcept
constexpr std::size_t size () const noexcept
constexpr void clear () noexcept
void assign (std::string_view rhs) noexcept
void append (std::string_view rhs) noexcept
template<typename TypeT >
auto operator<=> (const TypeT &rhs) const noexcept
template<typename TypeT >
bool operator== (const TypeT &rhs) const noexcept
Detailed Description
template<std::size_t MaxN>
class toolbox::util::StringBuf< MaxN >
String buffer with fixed upper-bound.
Definition at line 30 of file StringBuf.hpp.
Constructor & Destructor Documentation
StringBuf() [1/5]
template<std::size_t MaxN> template<std::size_t MaxR> toolbox::util::StringBuf< MaxN >::StringBuf (const StringBuf< MaxR > & rhs) inline noexcept
Definition at line 33 of file StringBuf.hpp.
StringBuf() [2/5]
template<std::size_t MaxN> toolbox::util::StringBuf< MaxN >::StringBuf (std::string_view rhs) inline explicit noexcept
Definition at line 37 of file StringBuf.hpp.
StringBuf() [3/5]
template<std::size_t MaxN> constexpr toolbox::util::StringBuf< MaxN >::StringBuf () constexpr default noexcept
~StringBuf()
template<std::size_t MaxN> toolbox::util::StringBuf< MaxN >::~StringBuf () default
StringBuf() [4/5]
template<std::size_t MaxN> toolbox::util::StringBuf< MaxN >::StringBuf (const StringBuf< MaxN > & rhs) inline noexcept
Definition at line 43 of file StringBuf.hpp.
StringBuf() [5/5]
template<std::size_t MaxN> constexpr toolbox::util::StringBuf< MaxN >::StringBuf (StringBuf< MaxN > &&) constexpr default noexcept
Member Function Documentation
operator=() [1/4]
template<std::size_t MaxN> StringBuf & toolbox::util::StringBuf< MaxN >::operator= (const StringBuf< MaxN > & rhs) inline noexcept
Definition at line 44 of file StringBuf.hpp.
operator=() [2/4]
template<std::size_t MaxN> constexpr StringBuf & toolbox::util::StringBuf< MaxN >::operator= (StringBuf< MaxN > &&) constexpr default noexcept
operator=() [3/4]
template<std::size_t MaxN> template<std::size_t MaxR> StringBuf & toolbox::util::StringBuf< MaxN >::operator= (const StringBuf< MaxR > & rhs) inline noexcept
Definition at line 55 of file StringBuf.hpp.
operator=() [4/4]
template<std::size_t MaxN> StringBuf & toolbox::util::StringBuf< MaxN >::operator= (std::string_view rhs) inline noexcept
Definition at line 60 of file StringBuf.hpp.
operator+=() [1/2]
template<std::size_t MaxN> template<std::size_t MaxR> StringBuf & toolbox::util::StringBuf< MaxN >::operator+= (const StringBuf< MaxR > & rhs) inline noexcept
Definition at line 66 of file StringBuf.hpp.
operator+=() [2/2]
template<std::size_t MaxN> StringBuf & toolbox::util::StringBuf< MaxN >::operator+= (std::string_view rhs) inline noexcept
Definition at line 71 of file StringBuf.hpp.
data()
template<std::size_t MaxN> constexpr const char * toolbox::util::StringBuf< MaxN >::data () const inline constexpr noexcept
Definition at line 77 of file StringBuf.hpp.
empty()
template<std::size_t MaxN> constexpr bool toolbox::util::StringBuf< MaxN >::empty () const inline constexpr noexcept
Definition at line 78 of file StringBuf.hpp.
size()
template<std::size_t MaxN> constexpr std::size_t toolbox::util::StringBuf< MaxN >::size () const inline constexpr noexcept
Definition at line 79 of file StringBuf.hpp.
Referenced by toolbox::util::StringBuf< MaxN >::operator==().
clear()
template<std::size_t MaxN> constexpr void toolbox::util::StringBuf< MaxN >::clear () inline constexpr noexcept
Definition at line 80 of file StringBuf.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
assign()
template<std::size_t MaxN> void toolbox::util::StringBuf< MaxN >::assign (std::string_view rhs) inline noexcept
Definition at line 82 of file StringBuf.hpp.
Referenced by toolbox::util::StringBuf< MaxN >::assign(), toolbox::util::StringBuf< MaxN >::operator=(), toolbox::util::StringBuf< MaxN >::operator=(), toolbox::util::StringBuf< MaxN >::operator=(), toolbox::util::StringBuf< MaxN >::StringBuf(), toolbox::util::StringBuf< MaxN >::StringBuf(), and toolbox::util::StringBuf< MaxN >::StringBuf().
append()
template<std::size_t MaxN> void toolbox::util::StringBuf< MaxN >::append (std::string_view rhs) inline noexcept
Definition at line 83 of file StringBuf.hpp.
Referenced by toolbox::util::StringBuf< MaxN >::append(), toolbox::util::StringBuf< MaxN >::operator+=(), and toolbox::util::StringBuf< MaxN >::operator+=().
operator<=>()
template<std::size_t MaxN> template<typename TypeT > auto toolbox::util::StringBuf< MaxN >::operator<=> (const TypeT & rhs) const inline noexcept
Definition at line 86 of file StringBuf.hpp.
operator==()
template<std::size_t MaxN> template<typename TypeT > bool toolbox::util::StringBuf< MaxN >::operator== (const TypeT & rhs) const inline noexcept
Definition at line 91 of file StringBuf.hpp.
The documentation for this class was generated from the following file:
toolbox/util/StringBuf.hpp