Toolbox: toolbox::http::StreamBuf Class Reference
toolbox::http::StreamBuf Class Reference final
#include <toolbox/http/Stream.hpp>
Public Member Functions
StreamBuf (Buffer &buf) noexcept
~StreamBuf () override
StreamBuf (const StreamBuf &)=delete
StreamBuf & operator= (const StreamBuf &)=delete
StreamBuf (StreamBuf &&)=delete
StreamBuf & operator= (StreamBuf &&)=delete
std::streamsize pcount () const noexcept
void commit () noexcept
void reset () noexcept
void set_content_length (std::streamsize pos, std::streamsize len) noexcept
Protected Member Functions
int_type overflow (int_type c) noexcept override
std::streamsize xsputn (const char_type *s, std::streamsize count) noexcept override
Detailed Description
Definition at line 31 of file Stream.hpp.
Constructor & Destructor Documentation
StreamBuf() [1/3]
toolbox::http::StreamBuf::StreamBuf (Buffer & buf) inline explicit noexcept
Definition at line 33 of file Stream.hpp.
~StreamBuf()
toolbox::http::StreamBuf::~StreamBuf () override default
StreamBuf() [2/3]
toolbox::http::StreamBuf::StreamBuf (const StreamBuf &) delete
StreamBuf() [3/3]
toolbox::http::StreamBuf::StreamBuf (StreamBuf &&) delete
Member Function Documentation
operator=() [1/2]
StreamBuf & toolbox::http::StreamBuf::operator= (const StreamBuf &) delete
operator=() [2/2]
StreamBuf & toolbox::http::StreamBuf::operator= (StreamBuf &&) delete
pcount()
std::streamsize toolbox::http::StreamBuf::pcount () const inline noexcept
Definition at line 47 of file Stream.hpp.
Referenced by toolbox::http::OStream::commit(), and toolbox::http::OStream::reset().
commit()
void toolbox::http::StreamBuf::commit () inline noexcept
Definition at line 48 of file Stream.hpp.
Referenced by toolbox::http::OStream::commit().
reset()
void toolbox::http::StreamBuf::reset () inline noexcept
Definition at line 49 of file Stream.hpp.
Referenced by toolbox::http::OStream::reset().
set_content_length()
void toolbox::http::StreamBuf::set_content_length (std::streamsize pos, std::streamsize len) noexcept
Definition at line 23 of file Stream.cpp.
Referenced by toolbox::http::OStream::commit().
overflow()
StreamBuf::int_type toolbox::http::StreamBuf::overflow (int_type c) override protected noexcept
Definition at line 35 of file Stream.cpp.
xsputn()
std::streamsize toolbox::http::StreamBuf::xsputn (const char_type * s, std::streamsize count) override protected noexcept
The documentation for this class was generated from the following files:
toolbox/http/Stream.hpp
toolbox/http/Stream.cpp