Toolbox: toolbox::util::ArgvSequence Class Reference
toolbox::util::ArgvSequence Class Reference
Utility class that allows an argv array to be treated as a sequence.
#include <toolbox/util/Argv.hpp>
Public Types
using ConstIterator = const char *const *
Public Member Functions
constexpr ArgvSequence (int argc, const char *const argv[])
~ArgvSequence ()=default
constexpr ArgvSequence (const ArgvSequence &) noexcept=default
constexpr ArgvSequence & operator= (const ArgvSequence &) noexcept=default
constexpr ArgvSequence (ArgvSequence &&) noexcept=default
constexpr ArgvSequence & operator= (ArgvSequence &&) noexcept=default
constexpr ConstIterator begin () const noexcept
constexpr ConstIterator end () const noexcept
Detailed Description
Utility class that allows an argv array to be treated as a sequence.
Definition at line 29 of file Argv.hpp.
Member Typedef Documentation
ConstIterator
using toolbox::util::ArgvSequence::ConstIterator = const char* const*
Definition at line 31 of file Argv.hpp.
Constructor & Destructor Documentation
ArgvSequence() [1/3]
constexpr toolbox::util::ArgvSequence::ArgvSequence (int argc, const char *const argv[]) inline
Definition at line 32 of file Argv.hpp.
~ArgvSequence()
toolbox::util::ArgvSequence::~ArgvSequence () default
Referenced by ArgvSequence().
ArgvSequence() [2/3]
constexpr toolbox::util::ArgvSequence::ArgvSequence (const ArgvSequence &) default noexcept
ArgvSequence() [3/3]
constexpr toolbox::util::ArgvSequence::ArgvSequence (ArgvSequence &&) default noexcept
Member Function Documentation
operator=() [1/2]
constexpr ArgvSequence& toolbox::util::ArgvSequence::operator= (const ArgvSequence &) default noexcept
Referenced by toolbox::util::ArgvLexer::ArgvLexer(), and ArgvSequence().
operator=() [2/2]
constexpr ArgvSequence& toolbox::util::ArgvSequence::operator= (ArgvSequence &&) default noexcept
begin()
constexpr ConstIterator toolbox::util::ArgvSequence::begin () const inline noexcept
Definition at line 47 of file Argv.hpp.
Referenced by toolbox::util::ArgvLexer::ArgvLexer().
end()
constexpr ConstIterator toolbox::util::ArgvSequence::end () const inline noexcept
Definition at line 48 of file Argv.hpp.
Referenced by toolbox::util::ArgvLexer::ArgvLexer().
The documentation for this class was generated from the following file:
toolbox/util/Argv.hpp