Toolbox: toolbox::util::Exception Class Reference
toolbox::util::Exception Class Reference
#include <toolbox/util/Exception.hpp>
Public Member Functions
Exception (std::error_code ec=std::error_code())
Exception (int err, const std::error_category &ecat)
Exception (std::error_code ec, std::string_view what)
Exception (int err, const std::error_category &ecat, std::string_view what)
~Exception () override
Exception (const Exception &)=default
Exception & operator= (const Exception &)=default
Exception (Exception &&)=default
Exception & operator= (Exception &&)=default
void to_json (std::ostream &os) const
const std::error_code & code () const noexcept
Returns the error code.
Static Public Member Functions
static void to_json (std::ostream &os, int code, const char *message)
static void to_json (std::ostream &os, const std::error_code &code, const char *message)
Detailed Description
Definition at line 32 of file Exception.hpp.
Constructor & Destructor Documentation
Exception() [1/6]
toolbox::util::Exception::Exception (std::error_code ec = std::error_code()) explicit
Definition at line 26 of file Exception.cpp.
Exception() [2/6]
toolbox::util::Exception::Exception (int err, const std::error_category & ecat)
Definition at line 31 of file Exception.cpp.
Exception() [3/6]
toolbox::util::Exception::Exception (std::error_code ec, std::string_view what)
Definition at line 35 of file Exception.cpp.
Exception() [4/6]
toolbox::util::Exception::Exception (int err, const std::error_category & ecat, std::string_view what)
Definition at line 40 of file Exception.cpp.
~Exception()
toolbox::util::Exception::~Exception () override default
Exception() [5/6]
toolbox::util::Exception::Exception (const Exception &) default
Exception() [6/6]
toolbox::util::Exception::Exception (Exception &&) default
Member Function Documentation
operator=() [1/2]
Exception& toolbox::util::Exception::operator= (const Exception &) default
operator=() [2/2]
Exception& toolbox::util::Exception::operator= (Exception &&) default
to_json() [1/3]
void toolbox::util::Exception::to_json (std::ostream & os, int code, const char * message) static
Format exception as a OpenAPI JSON response message.
Parameters
os The output stream.
code The error code.
message The error Message.
Definition at line 47 of file Exception.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
to_json() [2/3]
static void toolbox::util::Exception::to_json (std::ostream & os, const std::error_code & code, const char * message) inline static
Format exception as a OpenAPI JSON response message.
Parameters
os The output stream.
code The error code.
message The error Message.
Definition at line 58 of file Exception.hpp.
to_json() [3/3]
void toolbox::util::Exception::to_json (std::ostream & os) const inline
Format exception as a OpenAPI JSON response message.
Parameters
os The output stream.
Definition at line 65 of file Exception.hpp.
Referenced by to_json().
code()
const std::error_code& toolbox::util::Exception::code () const inline noexcept
Returns the error code.
Definition at line 68 of file Exception.hpp.
Referenced by to_json().
The documentation for this class was generated from the following files:
toolbox/util/Exception.hpp
toolbox/util/Exception.cpp