Toolbox: toolbox::util::OStream< MaxN > Class Template Reference
toolbox::util::OStream< MaxN > Class Template Reference final
OStream uses a dynamic storage acquired from the custom allocator.
#include <toolbox/util/Stream.hpp>
Public Member Functions
OStream (std::nullptr_t) noexcept
Constructor for initialising the StreamBuf with a null buffer.
OStream (StoragePtr< MaxN > storage) noexcept
Constructor for initialising the StreamBuf with pre-allocated storage.
OStream ()
Default constructor allocates required storage.
~OStream ()=default
OStream (const OStream &)=delete
OStream & operator= (const OStream &)=delete
OStream (OStream &&)=delete
OStream & operator= (OStream &&)=delete
const char * data () const noexcept
bool empty () const noexcept
std::size_t size () const noexcept
std::string_view str () const noexcept
operator bool () const noexcept
StoragePtr< MaxN > release_storage () noexcept
Release the managed storage.
void set_storage (StoragePtr< MaxN > storage) noexcept
Update the internal storage and clear i/o state.
void reset () noexcept
Reset the current position back to the beginning of the buffer.
Public Member Functions inherited from toolbox::util::OStreamBase< OStream< MaxN > >
OStream< MaxN > & put_data (const char *data, std::size_t data_size) noexcept
OStream< MaxN > & put_char (T ch) noexcept
OStream< MaxN > & put_num (bool val) noexcept
OStream< MaxN > & put_num (T val) noexcept
OStream< MaxN > & put_num (T val) noexcept
OStream< MaxN > & put (char ch) noexcept
For compatability with std::ostream API.
OStream< MaxN > & write (const char *data, std::size_t sz) noexcept
OStream< MaxN > & put_data (const char *data, std::size_t data_size) noexcept
OStream< MaxN > & put_char (T ch) noexcept
OStream< MaxN > & put_num (bool val) noexcept
OStream< MaxN > & put_num (T val) noexcept
OStream< MaxN > & put_num (T val) noexcept
OStream< MaxN > & put (char ch) noexcept
For compatability with std::ostream API.
OStream< MaxN > & write (const char *data, std::size_t sz) noexcept
Static Public Member Functions
static StoragePtr< MaxN > make_storage ()
Additional Inherited Members
Static Protected Attributes inherited from toolbox::util::OStreamBase< OStream< MaxN > >
static constexpr std::size_t PutNumMaxBufRequest
static constexpr std::size_t PutNumMaxBufRequest
Detailed Description
template<std::size_t MaxN>
class toolbox::util::OStream< MaxN >
OStream uses a dynamic storage acquired from the custom allocator.
Definition at line 38 of file Stream.hpp.
Constructor & Destructor Documentation
OStream() [1/5]
template<std::size_t MaxN> toolbox::util::OStream< MaxN >::OStream (std::nullptr_t) inline explicit noexcept
Constructor for initialising the StreamBuf with a null buffer.
Definition at line 41 of file Stream.hpp.
OStream() [2/5]
template<std::size_t MaxN> toolbox::util::OStream< MaxN >::OStream (StoragePtr< MaxN > storage) inline explicit noexcept
Constructor for initialising the StreamBuf with pre-allocated storage.
Definition at line 47 of file Stream.hpp.
OStream() [3/5]
template<std::size_t MaxN> toolbox::util::OStream< MaxN >::OStream () inline
Default constructor allocates required storage.
Definition at line 53 of file Stream.hpp.
~OStream()
template<std::size_t MaxN> toolbox::util::OStream< MaxN >::~OStream () default
OStream() [4/5]
template<std::size_t MaxN> toolbox::util::OStream< MaxN >::OStream (const OStream< MaxN > &) delete
OStream() [5/5]
template<std::size_t MaxN> toolbox::util::OStream< MaxN >::OStream (OStream< MaxN > &&) delete
Member Function Documentation
operator=() [1/2]
template<std::size_t MaxN> OStream & toolbox::util::OStream< MaxN >::operator= (const OStream< MaxN > &) delete
operator=() [2/2]
template<std::size_t MaxN> OStream & toolbox::util::OStream< MaxN >::operator= (OStream< MaxN > &&) delete
make_storage()
template<std::size_t MaxN> static StoragePtr< MaxN > toolbox::util::OStream< MaxN >::make_storage () inline static
Definition at line 64 of file Stream.hpp.
data()
template<std::size_t MaxN> const char * toolbox::util::OStream< MaxN >::data () const inline noexcept
Definition at line 65 of file Stream.hpp.
Referenced by toolbox::util::OStream< MaxN >::str().
empty()
template<std::size_t MaxN> bool toolbox::util::OStream< MaxN >::empty () const inline noexcept
Definition at line 66 of file Stream.hpp.
size()
template<std::size_t MaxN> std::size_t toolbox::util::OStream< MaxN >::size () const inline noexcept
Definition at line 67 of file Stream.hpp.
Referenced by toolbox::util::OStream< MaxN >::str().
str()
template<std::size_t MaxN> std::string_view toolbox::util::OStream< MaxN >::str () const inline noexcept
Definition at line 68 of file Stream.hpp.
operator bool()
template<std::size_t MaxN> toolbox::util::OStream< MaxN >::operator bool () const inline explicit noexcept
Definition at line 72 of file Stream.hpp.
release_storage()
template<std::size_t MaxN> StoragePtr< MaxN > toolbox::util::OStream< MaxN >::release_storage () inline noexcept
Release the managed storage.
Definition at line 77 of file Stream.hpp.
set_storage()
template<std::size_t MaxN> void toolbox::util::OStream< MaxN >::set_storage (StoragePtr< MaxN > storage) inline noexcept
Update the internal storage and clear i/o state.
Definition at line 86 of file Stream.hpp.
reset()
template<std::size_t MaxN> void toolbox::util::OStream< MaxN >::reset () inline noexcept
Reset the current position back to the beginning of the buffer.
Definition at line 93 of file Stream.hpp.
Referenced by toolbox::util::OStream< MaxN >::release_storage(), and toolbox::util::OStream< MaxN >::set_storage().
The documentation for this class was generated from the following file:
toolbox/util/Stream.hpp