Toolbox: toolbox::io::EventFd Class Reference
toolbox::io::EventFd Class Reference
#include <toolbox/io/EventFd.hpp>
Public Member Functions
EventFd (unsigned intval, int flags)
~EventFd ()=default
EventFd (const EventFd &)=delete
EventFd & operator= (const EventFd &)=delete
EventFd (EventFd &&) noexcept=default
EventFd & operator= (EventFd &&) noexcept=default
int fd () const noexcept
std::int64_t read ()
void write (std::int64_t val, std::error_code &ec) noexcept
void write (std::int64_t val)
Detailed Description
Definition at line 50 of file EventFd.hpp.
Constructor & Destructor Documentation
EventFd() [1/3]
toolbox::io::EventFd::EventFd (unsigned intval, int flags) inline
Definition at line 52 of file EventFd.hpp.
~EventFd()
toolbox::io::EventFd::~EventFd () default
EventFd() [2/3]
toolbox::io::EventFd::EventFd (const EventFd &) delete
EventFd() [3/3]
toolbox::io::EventFd::EventFd (EventFd &&) default noexcept
Member Function Documentation
operator=() [1/2]
EventFd & toolbox::io::EventFd::operator= (const EventFd &) delete
operator=() [2/2]
EventFd & toolbox::io::EventFd::operator= (EventFd &&) default noexcept
fd()
int toolbox::io::EventFd::fd () const inline noexcept
Definition at line 66 of file EventFd.hpp.
Referenced by toolbox::io::Reactor::Reactor(), and toolbox::io::Reactor::~Reactor().
read()
std::int64_t toolbox::io::EventFd::read () inline
Definition at line 67 of file EventFd.hpp.
write() [1/2]
void toolbox::io::EventFd::write (std::int64_t val, std::error_code & ec) inline noexcept
Definition at line 76 of file EventFd.hpp.
Referenced by toolbox::io::Reactor::do_wakeup().
write() [2/2]
void toolbox::io::EventFd::write (std::int64_t val) inline
Definition at line 86 of file EventFd.hpp.
The documentation for this class was generated from the following file:
toolbox/io/EventFd.hpp