Toolbox: toolbox::hdr::HdrIterator Class Reference
toolbox::hdr::HdrIterator Class Reference
HdrIterator is the base iterator for all iterator types.
#include <toolbox/hdr/Iterator.hpp>
Public Member Functions
HdrIterator (const HdrHistogram &h) noexcept
virtual ~HdrIterator ()
HdrIterator (const HdrIterator &)=delete
HdrIterator & operator= (const HdrIterator &)=delete
HdrIterator (HdrIterator &&) noexcept=default
HdrIterator & operator= (HdrIterator &&)=delete
std::int64_t count () const noexcept
Value directly from array for the current counts_index.
std::int64_t cumulative_count () const noexcept
Sum of all of the counts up to and including the count at this index.
std::int64_t value () const noexcept
The current value based on counts_index.
std::int64_t highest_equivalent_value () const noexcept
bool next () noexcept
Protected Member Functions
bool has_buckets () const noexcept
bool has_next () const noexcept
std::int64_t peek_next_value_from_index () const noexcept
bool next_value_greater_than_reporting_level_upper_bound (std::int64_t reporting_level_upper_bound) const noexcept
bool basic_next () noexcept
bool move_next () noexcept
void update_iterated_values (std::int64_t new_value_iterated_to) noexcept
virtual bool do_next () noexcept
Protected Attributes
const HdrHistogram & h_
std::int32_t counts_index_
Raw index into the counts array.
std::int64_t total_count_
Snapshot of the length at the time the iterator is created.
std::int64_t count_
std::int64_t cumulative_count_
std::int64_t value_
std::int64_t highest_equivalent_value_
std::int64_t lowest_equivalent_value_
std::int64_t median_equivalent_value_
std::int64_t value_iterated_from_
std::int64_t value_iterated_to_
Detailed Description
HdrIterator is the base iterator for all iterator types.
Definition at line 28 of file Iterator.hpp.
Constructor & Destructor Documentation
HdrIterator() [1/3]
toolbox::hdr::HdrIterator::HdrIterator (const HdrHistogram & h) noexcept
Construct iterator.
Parameters
h The histogram to iterate over.
Definition at line 26 of file Iterator.cpp.
~HdrIterator()
toolbox::hdr::HdrIterator::~HdrIterator () virtual default
HdrIterator() [2/3]
toolbox::hdr::HdrIterator::HdrIterator (const HdrIterator &) delete
HdrIterator() [3/3]
toolbox::hdr::HdrIterator::HdrIterator (HdrIterator &&) default noexcept
Member Function Documentation
operator=() [1/2]
HdrIterator& toolbox::hdr::HdrIterator::operator= (const HdrIterator &) delete
operator=() [2/2]
HdrIterator& toolbox::hdr::HdrIterator::operator= (HdrIterator &&) delete
count()
std::int64_t toolbox::hdr::HdrIterator::count () const inline noexcept
Value directly from array for the current counts_index.
Definition at line 45 of file Iterator.hpp.
Referenced by toolbox::hdr::mean(), toolbox::hdr::stddev(), and toolbox::hdr::value_at_percentile().
cumulative_count()
std::int64_t toolbox::hdr::HdrIterator::cumulative_count () const inline noexcept
Sum of all of the counts up to and including the count at this index.
Definition at line 47 of file Iterator.hpp.
value()
std::int64_t toolbox::hdr::HdrIterator::value () const inline noexcept
The current value based on counts_index.
Definition at line 49 of file Iterator.hpp.
highest_equivalent_value()
std::int64_t toolbox::hdr::HdrIterator::highest_equivalent_value () const inline noexcept
Definition at line 50 of file Iterator.hpp.
next()
bool toolbox::hdr::HdrIterator::next () inline noexcept
Iterate to the next value for the iterator. If there are no more values available return false.
Returns
false if there are no values remaining for this iterator.
Definition at line 56 of file Iterator.hpp.
has_buckets()
bool toolbox::hdr::HdrIterator::has_buckets () const protected noexcept
Definition at line 50 of file Iterator.cpp.
has_next()
bool toolbox::hdr::HdrIterator::has_next () const protected noexcept
Definition at line 55 of file Iterator.cpp.
Referenced by toolbox::hdr::HdrLinearIterator::do_next(), and toolbox::hdr::HdrLogIterator::do_next().
peek_next_value_from_index()
int64_t toolbox::hdr::HdrIterator::peek_next_value_from_index () const protected noexcept
Definition at line 60 of file Iterator.cpp.
next_value_greater_than_reporting_level_upper_bound()
bool toolbox::hdr::HdrIterator::next_value_greater_than_reporting_level_upper_bound (std::int64_t reporting_level_upper_bound) const protected noexcept
Definition at line 65 of file Iterator.cpp.
Referenced by toolbox::hdr::HdrLinearIterator::do_next(), and toolbox::hdr::HdrLogIterator::do_next().
basic_next()
bool toolbox::hdr::HdrIterator::basic_next () protected noexcept
Definition at line 74 of file Iterator.cpp.
Referenced by toolbox::hdr::HdrRecordedIterator::do_next().
move_next()
bool toolbox::hdr::HdrIterator::move_next () protected noexcept
Definition at line 83 of file Iterator.cpp.
Referenced by toolbox::hdr::HdrLinearIterator::do_next(), and toolbox::hdr::HdrLogIterator::do_next().
update_iterated_values()
void toolbox::hdr::HdrIterator::update_iterated_values (std::int64_t new_value_iterated_to) protected noexcept
Definition at line 101 of file Iterator.cpp.
Referenced by toolbox::hdr::HdrRecordedIterator::do_next(), toolbox::hdr::HdrLinearIterator::do_next(), and toolbox::hdr::HdrLogIterator::do_next().
do_next()
bool toolbox::hdr::HdrIterator::do_next () protected virtual noexcept
Reimplemented in toolbox::hdr::HdrLogIterator, toolbox::hdr::HdrLinearIterator, toolbox::hdr::HdrRecordedIterator, and toolbox::hdr::HdrPercentileIterator.
Definition at line 41 of file Iterator.cpp.
Member Data Documentation
h_
const HdrHistogram& toolbox::hdr::HdrIterator::h_ protected
Definition at line 71 of file Iterator.hpp.
Referenced by toolbox::hdr::HdrLinearIterator::do_next(), and toolbox::hdr::HdrLogIterator::do_next().
counts_index_
std::int32_t toolbox::hdr::HdrIterator::counts_index_ protected
Raw index into the counts array.
Definition at line 73 of file Iterator.hpp.
total_count_
std::int64_t toolbox::hdr::HdrIterator::total_count_ protected
Snapshot of the length at the time the iterator is created.
Definition at line 75 of file Iterator.hpp.
count_
std::int64_t toolbox::hdr::HdrIterator::count_ protected
Definition at line 76 of file Iterator.hpp.
Referenced by toolbox::hdr::HdrRecordedIterator::do_next(), toolbox::hdr::HdrLinearIterator::do_next(), and toolbox::hdr::HdrLogIterator::do_next().
cumulative_count_
std::int64_t toolbox::hdr::HdrIterator::cumulative_count_ protected
Definition at line 77 of file Iterator.hpp.
value_
std::int64_t toolbox::hdr::HdrIterator::value_ protected
Definition at line 78 of file Iterator.hpp.
Referenced by toolbox::hdr::HdrRecordedIterator::do_next(), toolbox::hdr::HdrLinearIterator::do_next(), and toolbox::hdr::HdrLogIterator::do_next().
highest_equivalent_value_
std::int64_t toolbox::hdr::HdrIterator::highest_equivalent_value_ protected
Definition at line 79 of file Iterator.hpp.
lowest_equivalent_value_
std::int64_t toolbox::hdr::HdrIterator::lowest_equivalent_value_ protected
Definition at line 80 of file Iterator.hpp.
median_equivalent_value_
std::int64_t toolbox::hdr::HdrIterator::median_equivalent_value_ protected
Definition at line 81 of file Iterator.hpp.
value_iterated_from_
std::int64_t toolbox::hdr::HdrIterator::value_iterated_from_ protected
Definition at line 82 of file Iterator.hpp.
value_iterated_to_
std::int64_t toolbox::hdr::HdrIterator::value_iterated_to_ protected
Definition at line 83 of file Iterator.hpp.
The documentation for this class was generated from the following files:
toolbox/hdr/Iterator.hpp
toolbox/hdr/Iterator.cpp