Toolbox: toolbox::io::Muxer Class Reference
toolbox::io::Muxer Class Reference
#include <toolbox/io/Muxer.hpp>
Public Types
using Event = epoll_event
Public Member Functions
Muxer (int flags=0)
~Muxer ()
Muxer (const Muxer &)=delete
Muxer & operator= (const Muxer &)=delete
Muxer (Muxer &&)=default
Muxer & operator= (Muxer &&)=default
void swap (Muxer &rhs) noexcept
int wait (Event buf[], std::size_t size, std::error_code &ec)
Returns the number of file descriptors that are ready.
int wait (Event buf[], std::size_t size, MonoTime timeout, std::error_code &ec)
void subscribe (int fd, int sid, unsigned events)
void unsubscribe (int fd) noexcept
void set_events (int fd, int sid, unsigned events, std::error_code &ec) noexcept
void set_events (int fd, int sid, unsigned events)
Static Public Member Functions
static constexpr int fd (const Event &ev) noexcept
static constexpr int sid (const Event &ev) noexcept
Detailed Description
Definition at line 31 of file Muxer.hpp.
Member Typedef Documentation
Event
using toolbox::io::Muxer::Event = epoll_event
Definition at line 33 of file Muxer.hpp.
Constructor & Destructor Documentation
Muxer() [1/3]
toolbox::io::Muxer::Muxer (int flags = 0) inline explicit
Definition at line 43 of file Muxer.hpp.
Referenced by ~Muxer().
~Muxer()
toolbox::io::Muxer::~Muxer () inline
Definition at line 49 of file Muxer.hpp.
Muxer() [2/3]
toolbox::io::Muxer::Muxer (const Muxer &) delete
Muxer() [3/3]
toolbox::io::Muxer::Muxer (Muxer &&) default
Member Function Documentation
fd()
static constexpr int toolbox::io::Muxer::fd (const Event & ev) inline static noexcept
Definition at line 35 of file Muxer.hpp.
Referenced by set_events(), and unsubscribe().
sid()
static constexpr int toolbox::io::Muxer::sid (const Event & ev) inline static noexcept
Definition at line 39 of file Muxer.hpp.
Referenced by set_events().
operator=() [1/2]
Muxer& toolbox::io::Muxer::operator= (const Muxer &) delete
Referenced by ~Muxer().
operator=() [2/2]
Muxer& toolbox::io::Muxer::operator= (Muxer &&) default
swap()
void toolbox::io::Muxer::swap (Muxer & rhs) inline noexcept
Definition at line 59 of file Muxer.hpp.
wait() [1/2]
int toolbox::io::Muxer::wait (Event buf[], std::size_t size, std::error_code & ec) inline
Returns the number of file descriptors that are ready.
Definition at line 61 of file Muxer.hpp.
wait() [2/2]
int toolbox::io::Muxer::wait (Event buf[], std::size_t size, MonoTime timeout, std::error_code & ec) inline
Returns the number of file descriptors that are ready, or zero if no file descriptor became ready during before the operation timed-out.
Definition at line 72 of file Muxer.hpp.
subscribe()
void toolbox::io::Muxer::subscribe (int fd, int sid, unsigned events) inline
Definition at line 82 of file Muxer.hpp.
Referenced by Muxer().
unsubscribe()
void toolbox::io::Muxer::unsubscribe (int fd) inline noexcept
Definition at line 88 of file Muxer.hpp.
Referenced by ~Muxer().
set_events() [1/2]
void toolbox::io::Muxer::set_events (int fd, int sid, unsigned events, std::error_code & ec) inline noexcept
Definition at line 96 of file Muxer.hpp.
Referenced by set_events(), and subscribe().
set_events() [2/2]
void toolbox::io::Muxer::set_events (int fd, int sid, unsigned events) inline
Definition at line 102 of file Muxer.hpp.
The documentation for this class was generated from the following file:
toolbox/io/Muxer.hpp