Toolbox: toolbox::util::Config Class Reference
toolbox::util::Config Class Reference
Simple config reader with environment variable substitution.
#include <toolbox/util/Config.hpp>
Public Member Functions
Config ()
~Config ()
Config (const Config &)
Config & operator= (const Config &)
Config (Config &&) noexcept
Config & operator= (Config &&) noexcept
const std::string & get (const std::string &key) const
Throws std::runtime_error if key does not exist.
const char * get (const std::string &key, const char *dfl) const
const char * get (const std::string &key, std::nullptr_t) const
template<typename ValueT >
ValueT get (const std::string &key) const
Throws std::runtime_error if key does not exist.
template<typename ValueT >
ValueT get (const std::string &key, ValueT dfl) const
auto get_multi (const std::string &key) const
template<typename ValueT >
auto get_multi (const std::string &key) const
std::size_t size () const noexcept
void clear () noexcept
std::istream & read_section (std::istream &is)
std::istream & read_section (std::istream &&is)
std::istream & read_section (std::istream &is, std::string &next)
std::istream & read_section (std::istream &&is, std::string &next)
void insert (std::string key, std::string val)
template<typename... ValueTs>
requires (toolbox::is_string_type_v<ValueTs> && ...)
void set (const std::string &key, ValueTs ... vals)
void set_parent (Config &parent) noexcept
Detailed Description
Simple config reader with environment variable substitution.
Definition at line 102 of file Config.hpp.
Constructor & Destructor Documentation
Config() [1/3]
toolbox::util::Config::Config () default
~Config()
toolbox::util::Config::~Config () default
Config() [2/3]
toolbox::util::Config::Config (const Config &) default
Config() [3/3]
toolbox::util::Config::Config (Config &&) default noexcept
Member Function Documentation
operator=() [1/2]
Config & toolbox::util::Config::operator= (const Config &) default
operator=() [2/2]
Config & toolbox::util::Config::operator= (Config &&) default noexcept
get() [1/5]
const std::string & toolbox::util::Config::get (const std::string & key) const
Throws std::runtime_error if key does not exist.
Definition at line 36 of file Config.cpp.
Referenced by get().
get() [2/5]
const char * toolbox::util::Config::get (const std::string & key, const char * dfl) const
Definition at line 48 of file Config.cpp.
get() [3/5]
const char * toolbox::util::Config::get (const std::string & key, std::nullptr_t) const inline
Definition at line 118 of file Config.hpp.
get() [4/5]
template<typename ValueT > ValueT toolbox::util::Config::get (const std::string & key) const inline
Throws std::runtime_error if key does not exist.
Definition at line 124 of file Config.hpp.
get() [5/5]
template<typename ValueT > ValueT toolbox::util::Config::get (const std::string & key, ValueT dfl) const inline
Definition at line 136 of file Config.hpp.
get_multi() [1/2]
auto toolbox::util::Config::get_multi (const std::string & key) const inline
Definition at line 145 of file Config.hpp.
get_multi() [2/2]
template<typename ValueT > auto toolbox::util::Config::get_multi (const std::string & key) const inline
Definition at line 160 of file Config.hpp.
size()
std::size_t toolbox::util::Config::size () const inline noexcept
Definition at line 164 of file Config.hpp.
clear()
void toolbox::util::Config::clear () inline noexcept
Definition at line 165 of file Config.hpp.
read_section() [1/4]
std::istream & toolbox::util::Config::read_section (std::istream & is) inline
Definition at line 166 of file Config.hpp.
Referenced by BOOST_AUTO_TEST_CASE(), toolbox::util::MultiConfig::read(), and read_section().
read_section() [2/4]
std::istream & toolbox::util::Config::read_section (std::istream && is) inline
Definition at line 167 of file Config.hpp.
Referenced by read_section().
read_section() [3/4]
std::istream & toolbox::util::Config::read_section (std::istream & is, std::string & next) inline
Definition at line 168 of file Config.hpp.
read_section() [4/4]
std::istream & toolbox::util::Config::read_section (std::istream && is, std::string & next) inline
Definition at line 172 of file Config.hpp.
insert()
void toolbox::util::Config::insert (std::string key, std::string val) inline
Definition at line 176 of file Config.hpp.
set()
template<typename... ValueTs> requires (toolbox::is_string_type_v<ValueTs> && ...) void toolbox::util::Config::set (const std::string & key, ValueTs ... vals) inline
Definition at line 184 of file Config.hpp.
set_parent()
void toolbox::util::Config::set_parent (Config & parent) inline noexcept
Definition at line 192 of file Config.hpp.
Referenced by toolbox::util::MultiConfig::read().
The documentation for this class was generated from the following files:
toolbox/util/Config.hpp
toolbox/util/Config.cpp