Toolbox: toolbox::benchmark::BenchmarkStore Class Reference
toolbox::benchmark::BenchmarkStore Class Reference
#include <toolbox/util/Benchmark.hpp>
Public Member Functions
void store (const char *name, Runnable &runnable)
void list () const
void run (const std::string &regex, bool randomise)
Static Public Member Functions
static BenchmarkStore & instance ()
Detailed Description
Definition at line 70 of file Benchmark.hpp.
Member Function Documentation
instance()
BenchmarkStore & toolbox::benchmark::BenchmarkStore::instance () static
Definition at line 27 of file Benchmark.cpp.
Referenced by toolbox::benchmark::Benchmark< FuncT >::Benchmark(), and toolbox::benchmark::detail::main().
store()
void toolbox::benchmark::BenchmarkStore::store (const char * name, Runnable & runnable)
Definition at line 33 of file Benchmark.cpp.
Referenced by toolbox::benchmark::Benchmark< FuncT >::Benchmark(), instance(), and toolbox::benchmark::detail::main().
list()
void toolbox::benchmark::BenchmarkStore::list () const
Definition at line 38 of file Benchmark.cpp.
Referenced by toolbox::benchmark::detail::main().
run()
void toolbox::benchmark::BenchmarkStore::run (const std::string & regex, bool randomise)
Definition at line 45 of file Benchmark.cpp.
The documentation for this class was generated from the following files:
toolbox/util/Benchmark.hpp
toolbox/util/Benchmark.cpp