Toolbox: toolbox::util::Tokeniser Class Reference
toolbox::util::Tokeniser Class Reference
#include <toolbox/util/Tokeniser.hpp>
Public Member Functions
constexpr Tokeniser (std::string_view buf, std::string_view delims) noexcept
constexpr Tokeniser () noexcept
constexpr ~Tokeniser ()=default
constexpr Tokeniser (const Tokeniser &) noexcept=default
constexpr Tokeniser & operator= (const Tokeniser &) noexcept=default
constexpr Tokeniser (Tokeniser &&) noexcept=default
constexpr Tokeniser & operator= (Tokeniser &&) noexcept=default
constexpr void reset (std::string_view buf, std::string_view delims) noexcept
constexpr std::size_t consumed () const noexcept
Returns total bytes consumed.
constexpr bool empty () const noexcept
Returns true if all bytes have been consumed.
constexpr bool has_delim () const noexcept
Returns true if a delimiter was found in the remaining data.
constexpr std::string_view top () const noexcept
constexpr std::string_view next () noexcept
constexpr void pop () noexcept
Detailed Description
Definition at line 28 of file Tokeniser.hpp.
Constructor & Destructor Documentation
Tokeniser() [1/4]
constexpr toolbox::util::Tokeniser::Tokeniser (std::string_view buf, std::string_view delims) inline constexpr noexcept
Definition at line 30 of file Tokeniser.hpp.
Tokeniser() [2/4]
constexpr toolbox::util::Tokeniser::Tokeniser () inline constexpr noexcept
Definition at line 34 of file Tokeniser.hpp.
~Tokeniser()
constexpr toolbox::util::Tokeniser::~Tokeniser () constexpr default
Tokeniser() [3/4]
constexpr toolbox::util::Tokeniser::Tokeniser (const Tokeniser &) constexpr default noexcept
Tokeniser() [4/4]
constexpr toolbox::util::Tokeniser::Tokeniser (Tokeniser &&) constexpr default noexcept
Member Function Documentation
operator=() [1/2]
constexpr Tokeniser & toolbox::util::Tokeniser::operator= (const Tokeniser &) constexpr default noexcept
operator=() [2/2]
constexpr Tokeniser & toolbox::util::Tokeniser::operator= (Tokeniser &&) constexpr default noexcept
reset()
constexpr void toolbox::util::Tokeniser::reset (std::string_view buf, std::string_view delims) inline constexpr noexcept
Definition at line 45 of file Tokeniser.hpp.
Referenced by Tokeniser().
consumed()
constexpr std::size_t toolbox::util::Tokeniser::consumed () const inline constexpr noexcept
Returns total bytes consumed.
Definition at line 53 of file Tokeniser.hpp.
empty()
constexpr bool toolbox::util::Tokeniser::empty () const inline constexpr noexcept
Returns true if all bytes have been consumed.
Definition at line 55 of file Tokeniser.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
has_delim()
constexpr bool toolbox::util::Tokeniser::has_delim () const inline constexpr noexcept
Returns true if a delimiter was found in the remaining data.
Definition at line 57 of file Tokeniser.hpp.
Referenced by BOOST_AUTO_TEST_CASE().
top()
constexpr std::string_view toolbox::util::Tokeniser::top () const inline constexpr noexcept
Definition at line 58 of file Tokeniser.hpp.
Referenced by next().
next()
constexpr std::string_view toolbox::util::Tokeniser::next () inline constexpr noexcept
Definition at line 62 of file Tokeniser.hpp.
pop()
constexpr void toolbox::util::Tokeniser::pop () inline constexpr noexcept
Definition at line 68 of file Tokeniser.hpp.
Referenced by next().
The documentation for this class was generated from the following file:
toolbox/util/Tokeniser.hpp