Toolbox: toolbox::http::BasicUrl< DerivedT > Class Template Reference
toolbox::http::BasicUrl< DerivedT > Class Template Reference
#include <toolbox/http/Url.hpp>
Public Member Functions
BasicUrl () noexcept
BasicUrl (const BasicUrl &) noexcept=default
BasicUrl & operator= (const BasicUrl &) noexcept=default
BasicUrl (BasicUrl &&) noexcept=default
BasicUrl & operator= (BasicUrl &&) noexcept=default
auto schema () const noexcept
auto host () const noexcept
auto port () const noexcept
auto path () const noexcept
auto query () const noexcept
auto fragment () const noexcept
auto user_info () const noexcept
Protected Member Functions
~BasicUrl ()=default
void reset () noexcept
void parse (bool is_connect=false)
Detailed Description
template<typename DerivedT>
class toolbox::http::BasicUrl< DerivedT >
Definition at line 28 of file Url.hpp.
Constructor & Destructor Documentation
BasicUrl() [1/3]
template<typename DerivedT> toolbox::http::BasicUrl< DerivedT >::BasicUrl () inline noexcept
Definition at line 30 of file Url.hpp.
Referenced by toolbox::http::BasicUrl< Url >::BasicUrl().
BasicUrl() [2/3]
template<typename DerivedT> toolbox::http::BasicUrl< DerivedT >::BasicUrl (const BasicUrl< DerivedT > &) default noexcept
BasicUrl() [3/3]
template<typename DerivedT> toolbox::http::BasicUrl< DerivedT >::BasicUrl (BasicUrl< DerivedT > &&) default noexcept
~BasicUrl()
template<typename DerivedT> toolbox::http::BasicUrl< DerivedT >::~BasicUrl () protected default
Referenced by toolbox::http::BasicUrl< Url >::user_info().
Member Function Documentation
operator=() [1/2]
template<typename DerivedT> BasicUrl& toolbox::http::BasicUrl< DerivedT >::operator= (const BasicUrl< DerivedT > &) default noexcept
Referenced by toolbox::http::BasicUrl< Url >::BasicUrl(), toolbox::http::Url::Url(), and toolbox::http::UrlView::UrlView().
operator=() [2/2]
template<typename DerivedT> BasicUrl& toolbox::http::BasicUrl< DerivedT >::operator= (BasicUrl< DerivedT > &&) default noexcept
schema()
template<typename DerivedT> auto toolbox::http::BasicUrl< DerivedT >::schema () const inline noexcept
Definition at line 40 of file Url.hpp.
host()
template<typename DerivedT> auto toolbox::http::BasicUrl< DerivedT >::host () const inline noexcept
Definition at line 45 of file Url.hpp.
port()
template<typename DerivedT> auto toolbox::http::BasicUrl< DerivedT >::port () const inline noexcept
Definition at line 50 of file Url.hpp.
path()
template<typename DerivedT> auto toolbox::http::BasicUrl< DerivedT >::path () const inline noexcept
Definition at line 55 of file Url.hpp.
query()
template<typename DerivedT> auto toolbox::http::BasicUrl< DerivedT >::query () const inline noexcept
Definition at line 60 of file Url.hpp.
fragment()
template<typename DerivedT> auto toolbox::http::BasicUrl< DerivedT >::fragment () const inline noexcept
Definition at line 65 of file Url.hpp.
user_info()
template<typename DerivedT> auto toolbox::http::BasicUrl< DerivedT >::user_info () const inline noexcept
Definition at line 70 of file Url.hpp.
reset()
template<typename DerivedT> void toolbox::http::BasicUrl< DerivedT >::reset () inline protected noexcept
Definition at line 79 of file Url.hpp.
parse()
template<typename DerivedT> void toolbox::http::BasicUrl< DerivedT >::parse (bool is_connect = false) inline protected
Definition at line 80 of file Url.hpp.
Referenced by toolbox::http::Url::Url(), and toolbox::http::UrlView::UrlView().
The documentation for this class was generated from the following file:
toolbox/http/Url.hpp