Toolbox: toolbox::util::Storage< SizeN > Class Template Reference
toolbox::util::Storage< SizeN > Class Template Reference
Storage represents a dynamic block of storage acquired from the custom allocator.
#include <toolbox/util/Storage.hpp>
Public Types
using value_type = char
using pointer = char *
using const_pointer = const char *
using reference = char &
using const_reference = const char &
using iterator = char *
using const_iterator = const char *
using reverse_iterator = std::reverse_iterator< iterator >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using difference_type = std::ptrdiff_t
using size_type = std::size_t
Public Member Functions
constexpr iterator begin () noexcept
constexpr const_iterator begin () const noexcept
constexpr iterator end () noexcept
constexpr const_iterator end () const noexcept
constexpr reverse_iterator rbegin () noexcept
constexpr const_reverse_iterator rbegin () const noexcept
constexpr reverse_iterator rend () noexcept
constexpr const_reverse_iterator rend () const noexcept
constexpr const_iterator cbegin () const noexcept
constexpr const_iterator cend () const noexcept
constexpr const_reverse_iterator crbegin () const noexcept
constexpr const_reverse_iterator crend () const noexcept
constexpr size_type size () const noexcept
constexpr size_type max_size () const noexcept
constexpr reference operator[] (size_type pos) noexcept
constexpr const_reference operator[] (size_type pos) const noexcept
constexpr pointer data () noexcept
constexpr const_pointer data () const noexcept
Additional Inherited Members
Static Public Member Functions inherited from toolbox::util::Allocator
static void * operator new (std::size_t size)
static void * operator new (std::size_t size, std::align_val_t al)
static void operator delete (void *ptr, std::size_t size) noexcept
static void operator delete (void *ptr, std::size_t size, std::align_val_t al) noexcept
Protected Member Functions inherited from toolbox::util::Allocator
~Allocator ()=default
Detailed Description
template<std::size_t SizeN>
class toolbox::util::Storage< SizeN >
Storage represents a dynamic block of storage acquired from the custom allocator.
Definition at line 29 of file Storage.hpp.
Member Typedef Documentation
value_type
template<std::size_t SizeN> using toolbox::util::Storage< SizeN >::value_type = char
Definition at line 31 of file Storage.hpp.
pointer
template<std::size_t SizeN> using toolbox::util::Storage< SizeN >::pointer = char*
Definition at line 33 of file Storage.hpp.
const_pointer
template<std::size_t SizeN> using toolbox::util::Storage< SizeN >::const_pointer = const char*
Definition at line 34 of file Storage.hpp.
reference
template<std::size_t SizeN> using toolbox::util::Storage< SizeN >::reference = char&
Definition at line 36 of file Storage.hpp.
const_reference
template<std::size_t SizeN> using toolbox::util::Storage< SizeN >::const_reference = const char&
Definition at line 37 of file Storage.hpp.
iterator
template<std::size_t SizeN> using toolbox::util::Storage< SizeN >::iterator = char*
Definition at line 39 of file Storage.hpp.
const_iterator
template<std::size_t SizeN> using toolbox::util::Storage< SizeN >::const_iterator = const char*
Definition at line 40 of file Storage.hpp.
reverse_iterator
template<std::size_t SizeN> using toolbox::util::Storage< SizeN >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 42 of file Storage.hpp.
const_reverse_iterator
template<std::size_t SizeN> using toolbox::util::Storage< SizeN >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 43 of file Storage.hpp.
difference_type
template<std::size_t SizeN> using toolbox::util::Storage< SizeN >::difference_type = std::ptrdiff_t
Definition at line 45 of file Storage.hpp.
size_type
template<std::size_t SizeN> using toolbox::util::Storage< SizeN >::size_type = std::size_t
Definition at line 46 of file Storage.hpp.
Member Function Documentation
begin() [1/2]
template<std::size_t SizeN> constexpr iterator toolbox::util::Storage< SizeN >::begin () inline constexpr noexcept
Definition at line 48 of file Storage.hpp.
Referenced by toolbox::util::Storage< SizeN >::crend(), and toolbox::util::Storage< SizeN >::rend().
begin() [2/2]
template<std::size_t SizeN> constexpr const_iterator toolbox::util::Storage< SizeN >::begin () const inline constexpr noexcept
Definition at line 49 of file Storage.hpp.
end() [1/2]
template<std::size_t SizeN> constexpr iterator toolbox::util::Storage< SizeN >::end () inline constexpr noexcept
Definition at line 50 of file Storage.hpp.
Referenced by toolbox::util::Storage< SizeN >::crbegin(), and toolbox::util::Storage< SizeN >::rbegin().
end() [2/2]
template<std::size_t SizeN> constexpr const_iterator toolbox::util::Storage< SizeN >::end () const inline constexpr noexcept
Definition at line 51 of file Storage.hpp.
rbegin() [1/2]
template<std::size_t SizeN> constexpr reverse_iterator toolbox::util::Storage< SizeN >::rbegin () inline constexpr noexcept
Definition at line 52 of file Storage.hpp.
rbegin() [2/2]
template<std::size_t SizeN> constexpr const_reverse_iterator toolbox::util::Storage< SizeN >::rbegin () const inline constexpr noexcept
Definition at line 53 of file Storage.hpp.
rend() [1/2]
template<std::size_t SizeN> constexpr reverse_iterator toolbox::util::Storage< SizeN >::rend () inline constexpr noexcept
Definition at line 57 of file Storage.hpp.
rend() [2/2]
template<std::size_t SizeN> constexpr const_reverse_iterator toolbox::util::Storage< SizeN >::rend () const inline constexpr noexcept
Definition at line 58 of file Storage.hpp.
cbegin()
template<std::size_t SizeN> constexpr const_iterator toolbox::util::Storage< SizeN >::cbegin () const inline constexpr noexcept
Definition at line 62 of file Storage.hpp.
cend()
template<std::size_t SizeN> constexpr const_iterator toolbox::util::Storage< SizeN >::cend () const inline constexpr noexcept
Definition at line 63 of file Storage.hpp.
crbegin()
template<std::size_t SizeN> constexpr const_reverse_iterator toolbox::util::Storage< SizeN >::crbegin () const inline constexpr noexcept
Definition at line 64 of file Storage.hpp.
crend()
template<std::size_t SizeN> constexpr const_reverse_iterator toolbox::util::Storage< SizeN >::crend () const inline constexpr noexcept
Definition at line 68 of file Storage.hpp.
size()
template<std::size_t SizeN> constexpr size_type toolbox::util::Storage< SizeN >::size () const inline constexpr noexcept
Definition at line 72 of file Storage.hpp.
max_size()
template<std::size_t SizeN> constexpr size_type toolbox::util::Storage< SizeN >::max_size () const inline constexpr noexcept
Definition at line 73 of file Storage.hpp.
operator[]() [1/2]
template<std::size_t SizeN> constexpr reference toolbox::util::Storage< SizeN >::operator[] (size_type pos) inline constexpr noexcept
Definition at line 74 of file Storage.hpp.
operator[]() [2/2]
template<std::size_t SizeN> constexpr const_reference toolbox::util::Storage< SizeN >::operator[] (size_type pos) const inline constexpr noexcept
Definition at line 75 of file Storage.hpp.
data() [1/2]
template<std::size_t SizeN> constexpr pointer toolbox::util::Storage< SizeN >::data () inline constexpr noexcept
Definition at line 76 of file Storage.hpp.
Referenced by toolbox::util::Storage< SizeN >::begin(), toolbox::util::Storage< SizeN >::cbegin(), toolbox::util::Storage< SizeN >::cend(), and toolbox::util::Storage< SizeN >::end().
data() [2/2]
template<std::size_t SizeN> constexpr const_pointer toolbox::util::Storage< SizeN >::data () const inline constexpr noexcept
Definition at line 77 of file Storage.hpp.
The documentation for this class was generated from the following file:
toolbox/util/Storage.hpp