Toolbox: toolbox::util::StaticStreamBuf< MaxN > Class Template Reference
toolbox::util::StaticStreamBuf< MaxN > Class Template Reference final
#include <toolbox/util/Stream.hpp>
Public Member Functions
StaticStreamBuf () noexcept
~StaticStreamBuf () override=default
StaticStreamBuf (const StaticStreamBuf &)=delete
StaticStreamBuf & operator= (const StaticStreamBuf &)=delete
StaticStreamBuf (StaticStreamBuf &&)=delete
StaticStreamBuf & operator= (StaticStreamBuf &&)=delete
const char * data () const noexcept
bool empty () const noexcept
std::size_t size () const noexcept
std::string_view str () const noexcept
void reset () noexcept
Reset the current position back to the beginning of the buffer.
Detailed Description
template<std::size_t MaxN>
class toolbox::util::StaticStreamBuf< MaxN >
Definition at line 147 of file Stream.hpp.
Constructor & Destructor Documentation
StaticStreamBuf() [1/3]
template<std::size_t MaxN> toolbox::util::StaticStreamBuf< MaxN >::StaticStreamBuf () inline noexcept
Definition at line 149 of file Stream.hpp.
~StaticStreamBuf()
template<std::size_t MaxN> toolbox::util::StaticStreamBuf< MaxN >::~StaticStreamBuf () override default
StaticStreamBuf() [2/3]
template<std::size_t MaxN> toolbox::util::StaticStreamBuf< MaxN >::StaticStreamBuf (const StaticStreamBuf< MaxN > &) delete
StaticStreamBuf() [3/3]
template<std::size_t MaxN> toolbox::util::StaticStreamBuf< MaxN >::StaticStreamBuf (StaticStreamBuf< MaxN > &&) delete
Member Function Documentation
operator=() [1/2]
template<std::size_t MaxN> StaticStreamBuf & toolbox::util::StaticStreamBuf< MaxN >::operator= (const StaticStreamBuf< MaxN > &) delete
operator=() [2/2]
template<std::size_t MaxN> StaticStreamBuf & toolbox::util::StaticStreamBuf< MaxN >::operator= (StaticStreamBuf< MaxN > &&) delete
data()
template<std::size_t MaxN> const char * toolbox::util::StaticStreamBuf< MaxN >::data () const inline noexcept
Definition at line 160 of file Stream.hpp.
Referenced by toolbox::util::StaticStreamBuf< MaxN >::str().
empty()
template<std::size_t MaxN> bool toolbox::util::StaticStreamBuf< MaxN >::empty () const inline noexcept
Definition at line 161 of file Stream.hpp.
size()
template<std::size_t MaxN> std::size_t toolbox::util::StaticStreamBuf< MaxN >::size () const inline noexcept
Definition at line 162 of file Stream.hpp.
Referenced by toolbox::util::StaticStreamBuf< MaxN >::str().
str()
template<std::size_t MaxN> std::string_view toolbox::util::StaticStreamBuf< MaxN >::str () const inline noexcept
Definition at line 164 of file Stream.hpp.
reset()
template<std::size_t MaxN> void toolbox::util::StaticStreamBuf< MaxN >::reset () inline noexcept
Reset the current position back to the beginning of the buffer.
Definition at line 166 of file Stream.hpp.
Referenced by toolbox::util::StaticStreamBuf< MaxN >::StaticStreamBuf().
The documentation for this class was generated from the following file:
toolbox/util/Stream.hpp