Toolbox: toolbox::http Namespace Reference
toolbox::http Namespace Reference
Classes
class BasicHttpConn
class BasicHttpParser
class BasicHttpServ
class BasicUrl
class HttpAppBase
class HttpBuf
struct HttpException
class HttpRequest
class HttpStream
class Url
class UrlView
Typedefs
using HttpConn = BasicHttpConn< HttpRequest, HttpAppBase >
using HttpHeaders = std::vector< std::pair< std::string, std::string > >
using HttpServ = BasicHttpServ< HttpConn, HttpAppBase >
Enumerations
enum First : bool { First::No = false, First::Yes = true }
enum NoCache : bool { NoCache::No = false, NoCache::Yes = true }
enum HttpMethod : int {
HttpMethod::Delete = HTTP_DELETE, HttpMethod::Get = HTTP_GET, HttpMethod::Head = HTTP_HEAD, HttpMethod::Post = HTTP_POST,
HttpMethod::Put = HTTP_PUT, HttpMethod::Connect = HTTP_CONNECT, HttpMethod::Options = HTTP_OPTIONS, HttpMethod::Trace = HTTP_TRACE,
HttpMethod::Copy = HTTP_COPY, HttpMethod::Lock = HTTP_LOCK, HttpMethod::MkCol = HTTP_MKCOL, HttpMethod::Move = HTTP_MOVE,
HttpMethod::PropFind = HTTP_PROPFIND, HttpMethod::PropPatch = HTTP_PROPPATCH, HttpMethod::Search = HTTP_SEARCH, HttpMethod::Unlock = HTTP_UNLOCK,
HttpMethod::Bind = HTTP_BIND, HttpMethod::Rebind = HTTP_REBIND, HttpMethod::Unbind = HTTP_UNBIND, HttpMethod::Acl = HTTP_ACL,
HttpMethod::Report = HTTP_REPORT, HttpMethod::MkActivity = HTTP_MKACTIVITY, HttpMethod::Checkout = HTTP_CHECKOUT, HttpMethod::Merge = HTTP_MERGE,
HttpMethod::MSearch = HTTP_MSEARCH, HttpMethod::Notify = HTTP_NOTIFY, HttpMethod::Subscribe = HTTP_SUBSCRIBE, HttpMethod::Unsubscribe = HTTP_UNSUBSCRIBE,
HttpMethod::Patch = HTTP_PATCH, HttpMethod::Purge = HTTP_PURGE, HttpMethod::MkCalendar = HTTP_MKCALENDAR, HttpMethod::Link = HTTP_LINK,
HttpMethod::Unlink = HTTP_UNLINK, HttpMethod::Source = HTTP_SOURCE
}
enum HttpStatus : int {
HttpStatus::Ok = HTTP_STATUS_OK, HttpStatus::NoContent = HTTP_STATUS_NO_CONTENT, HttpStatus::BadRequest = HTTP_STATUS_BAD_REQUEST, HttpStatus::Unauthorized = HTTP_STATUS_UNAUTHORIZED,
HttpStatus::Forbidden = HTTP_STATUS_FORBIDDEN, HttpStatus::NotFound = HTTP_STATUS_NOT_FOUND, HttpStatus::MethodNotAllowed = HTTP_STATUS_METHOD_NOT_ALLOWED, HttpStatus::InternalServerError = HTTP_STATUS_INTERNAL_SERVER_ERROR,
HttpStatus::ServiceUnavailable = HTTP_STATUS_SERVICE_UNAVAILABLE
}
enum HttpType : int { HttpType::Request = HTTP_REQUEST, HttpType::Response = HTTP_RESPONSE }
Functions
const std::error_category & http_error_category () noexcept
std::error_code make_error_code (HttpStatus status)
HttpStatus http_status (const std::error_code &ec)
const char * enum_string (HttpStatus status) noexcept
const char * enum_string (HttpMethod method) noexcept
std::ostream & operator<< (std::ostream &os, HttpMethod method)
std::ostream & operator<< (std::ostream &os, HttpStatus status)
Variables
constexpr char ApplicationJson [] {"application/json"}
constexpr char TextHtml [] {"text/html"}
constexpr char TextPlain [] {"text/plain"}
Typedef Documentation
HttpConn
using toolbox::http::HttpConn = typedef BasicHttpConn<HttpRequest, HttpAppBase>
Definition at line 241 of file Conn.hpp.
HttpHeaders
using toolbox::http::HttpHeaders = typedef std::vector<std::pair<std::string, std::string> >
Definition at line 28 of file Request.hpp.
HttpServ
using toolbox::http::HttpServ = typedef BasicHttpServ<HttpConn, HttpAppBase>
Definition at line 76 of file Serv.hpp.
Enumeration Type Documentation
First
enum toolbox::http::First : bool strong
Enumerator
No
Yes
Definition at line 27 of file Types.hpp.
NoCache
enum toolbox::http::NoCache : bool strong
Enumerator
No
Yes
Definition at line 29 of file Types.hpp.
HttpMethod
enum toolbox::http::HttpMethod : int strong
Enumerator
Delete
Get
Head
Post
Put
Connect
Options
Trace
Copy
Lock
MkCol
Move
PropFind
PropPatch
Search
Unlock
Bind
Rebind
Unbind
Acl
Report
MkActivity
Checkout
Merge
MSearch
Notify
Subscribe
Unsubscribe
Patch
Purge
MkCalendar
Link
Unlink
Source
Definition at line 31 of file Types.hpp.
HttpStatus
enum toolbox::http::HttpStatus : int strong
Enumerator
Ok
NoContent
BadRequest
Unauthorized
Forbidden
NotFound
MethodNotAllowed
InternalServerError
ServiceUnavailable
Definition at line 78 of file Types.hpp.
HttpType
enum toolbox::http::HttpType : int strong
Enumerator
Request
Response
Definition at line 97 of file Types.hpp.
Function Documentation
http_error_category()
TOOLBOX_API const std::error_category & toolbox::http::http_error_category () noexcept
Definition at line 42 of file Error.cpp.
Referenced by http_status().
make_error_code()
TOOLBOX_API std::error_code toolbox::http::make_error_code (HttpStatus status)
Definition at line 47 of file Error.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
http_status()
TOOLBOX_API HttpStatus toolbox::http::http_status (const std::error_code & ec)
Definition at line 52 of file Error.cpp.
enum_string() [1/2]
TOOLBOX_API const char * toolbox::http::enum_string (HttpStatus status) noexcept
Definition at line 22 of file Types.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), operator<<(), and toolbox::http::HttpStream::reset().
enum_string() [2/2]
const char* toolbox::http::enum_string (HttpMethod method) inline noexcept
Definition at line 68 of file Types.hpp.
operator<<() [1/2]
std::ostream& toolbox::http::operator<< (std::ostream & os, HttpMethod method) inline
Definition at line 73 of file Types.hpp.
operator<<() [2/2]
std::ostream& toolbox::http::operator<< (std::ostream & os, HttpStatus status) inline
Definition at line 92 of file Types.hpp.
Variable Documentation
ApplicationJson
constexpr char toolbox::http::ApplicationJson[] {"application/json"}
Definition at line 27 of file Stream.hpp.
TextHtml
constexpr char toolbox::http::TextHtml[] {"text/html"}
Definition at line 28 of file Stream.hpp.
TextPlain
constexpr char toolbox::http::TextPlain[] {"text/plain"}
Definition at line 29 of file Stream.hpp.