Toolbox: toolbox::hdr Namespace Reference
toolbox::hdr Namespace Reference
A C++ port of HdrHistogram_c written Michael Barker and released to the public domain.
Classes
struct HdrBucketConfig
Bucket configuration.
class HdrCountAddedIterator
HdrCountAddedIterator is a recorded value iterator.
class HdrHistogram
A High Dynamic Range (HDR) Histogram.
class HdrIterator
HdrIterator is the base iterator for all iterator types.
class HdrLinearIterator
HdrLinearIterator is a linear value iterator.
class HdrLogIterator
HdrLogIterator is a logarithmic value iterator.
class HdrPercentileIterator
HdrPercentileIterator is a percentile iterator.
class HdrRecordedIterator
HdrRecordedIterator is a recorded value iterator.
struct PutPercentiles
Functions
int64_t min (const HdrHistogram &h) noexcept
int64_t max (const HdrHistogram &h) noexcept
int64_t value_at_percentile (const HdrHistogram &h, double percentile) noexcept
double mean (const HdrHistogram &h) noexcept
double stddev (const HdrHistogram &h) noexcept
ostream & operator<< (ostream &os, PutPercentiles pp)
auto put_percentiles (const HdrHistogram &h, std::int32_t ticks_per_half_distance, double value_scale) noexcept
Detailed Description
A C++ port of HdrHistogram_c written Michael Barker and released to the public domain.
Function Documentation
min()
TOOLBOX_API std::int64_t toolbox::hdr::min (const HdrHistogram & h) noexcept
Definition at line 41 of file Utility.cpp.
Referenced by toolbox::io::advance(), toolbox::util::VarAccum::append(), BOOST_AUTO_TEST_CASE(), toolbox::util::VarAccum::clear(), toolbox::sys::close_all(), toolbox::hdr::HdrHistogram::counts_len(), toolbox::io::Buffer::data(), toolbox::io::Reactor::do_notify(), toolbox::util::IntPolicy< ValueT >::min(), toolbox::util::IntWrapper< PolicyT >::min(), toolbox::util::StringBuf< MaxN >::operator+=(), toolbox::util::pstrcpy(), toolbox::hdr::HdrHistogram::record_values(), toolbox::net::Resolver::run(), and toolbox::io::Buffer::str().
max()
TOOLBOX_API std::int64_t toolbox::hdr::max (const HdrHistogram & h) noexcept
Definition at line 46 of file Utility.cpp.
Referenced by toolbox::util::VarAccum::append(), BOOST_AUTO_TEST_CASE(), toolbox::util::VarAccum::clear(), toolbox::hdr::HdrHistogram::counts_len(), toolbox::io::TimerQueue::dispatch(), toolbox::ipc::futex_notify_all(), toolbox::hdr::HdrHistogram::HdrHistogram(), toolbox::util::IntPolicy< ValueT >::max(), toolbox::sys::MonoClock::max(), toolbox::util::IntWrapper< PolicyT >::max(), toolbox::sys::WallClock::max(), toolbox::io::Reactor::poll(), toolbox::hdr::HdrHistogram::record_values(), toolbox::hdr::HdrHistogram::reset(), and toolbox::sys::set_log_level().
value_at_percentile()
TOOLBOX_API std::int64_t toolbox::hdr::value_at_percentile (const HdrHistogram & h, double percentile) noexcept
Get the value at a specific percentile.
Parameters
h The histogram.
percentile The percentile to get the value for.
Returns
the percentile value.
Definition at line 51 of file Utility.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and toolbox::bm::BenchmarkSuite::report().
mean()
TOOLBOX_API double toolbox::hdr::mean (const HdrHistogram & h) noexcept
Gets the mean for the values in the histogram.
Parameters
h The histogram.
Returns
the mean.
Definition at line 66 of file Utility.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), operator<<(), toolbox::util::pctile95(), toolbox::util::pctile99(), toolbox::util::pctile999(), stddev(), and toolbox::util::zscore().
stddev()
TOOLBOX_API double toolbox::hdr::stddev (const HdrHistogram & h) noexcept
Gets the standard deviation for the values in the histogram.
Parameters
h The histogram.
Returns
the standard deviation.
Definition at line 80 of file Utility.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and operator<<().
operator<<()
TOOLBOX_API std::ostream & toolbox::hdr::operator<< (ostream & os, PutPercentiles pp)
Definition at line 96 of file Utility.cpp.
Referenced by put_percentiles().
put_percentiles()
auto toolbox::hdr::put_percentiles (const HdrHistogram & h, std::int32_t ticks_per_half_distance, double value_scale) inline noexcept
Definition at line 56 of file Utility.hpp.