Toolbox: toolbox::net::Sock Struct Reference
toolbox::net::Sock Struct Reference
#include <toolbox/net/Socket.hpp>
Public Member Functions
Sock (FileHandle &&sock, int family)
Sock () noexcept=default
int family () const noexcept
bool is_ip_family () const noexcept
std::error_code get_error (std::error_code &ec) const noexcept
std::error_code get_error () const
int get_rcv_buf (std::error_code &ec) const noexcept
int get_rcv_buf () const
int get_snd_buf (std::error_code &ec) const noexcept
int get_snd_buf () const
bool is_tcp_no_delay (std::error_code &ec) const noexcept
bool is_tcp_no_delay () const
void close ()
void set_non_block (std::error_code &ec) noexcept
void set_non_block ()
void set_rcv_buf (int size, std::error_code &ec) noexcept
void set_rcv_buf (int size)
void set_reuse_addr (bool enabled, std::error_code &ec) noexcept
void set_reuse_addr (bool enabled)
void set_snd_buf (int size, std::error_code &ec) noexcept
void set_snd_buf (int size)
void enable_hardware_rcv_timestamps ()
void enable_hardware_rcv_timestamps (std::error_code &ec) noexcept
void disable_hardware_rcv_timestamps ()
void disable_hardware_rcv_timestamps (std::error_code &ec) noexcept
Detailed Description
Definition at line 846 of file Socket.hpp.
Constructor & Destructor Documentation
Sock() [1/2]
toolbox::net::Sock::Sock (FileHandle && sock, int family) inline
Definition at line 847 of file Socket.hpp.
Sock() [2/2]
toolbox::net::Sock::Sock () default noexcept
Member Function Documentation
family()
int toolbox::net::Sock::family () const inline noexcept
Definition at line 854 of file Socket.hpp.
Referenced by toolbox::net::StreamSockServ::accept(), toolbox::net::StreamSockServ::accept(), toolbox::net::McastSock::set_ip_mcast_if(), toolbox::net::McastSock::set_ip_mcast_if(), toolbox::net::McastSock::set_ip_mcast_loop(), toolbox::net::McastSock::set_ip_mcast_loop(), toolbox::net::McastSock::set_ip_mcast_ttl(), toolbox::net::McastSock::set_ip_mcast_ttl(), and toolbox::net::StreamAcceptor< DerivedT >::~StreamAcceptor().
is_ip_family()
bool toolbox::net::Sock::is_ip_family () const inline noexcept
Definition at line 855 of file Socket.hpp.
get_error() [1/2]
std::error_code toolbox::net::Sock::get_error (std::error_code & ec) const inline noexcept
Definition at line 858 of file Socket.hpp.
get_error() [2/2]
std::error_code toolbox::net::Sock::get_error () const inline
Definition at line 862 of file Socket.hpp.
get_rcv_buf() [1/2]
int toolbox::net::Sock::get_rcv_buf (std::error_code & ec) const inline noexcept
Definition at line 864 of file Socket.hpp.
get_rcv_buf() [2/2]
int toolbox::net::Sock::get_rcv_buf () const inline
Definition at line 868 of file Socket.hpp.
get_snd_buf() [1/2]
int toolbox::net::Sock::get_snd_buf (std::error_code & ec) const inline noexcept
Definition at line 870 of file Socket.hpp.
get_snd_buf() [2/2]
int toolbox::net::Sock::get_snd_buf () const inline
Definition at line 874 of file Socket.hpp.
is_tcp_no_delay() [1/2]
bool toolbox::net::Sock::is_tcp_no_delay (std::error_code & ec) const inline noexcept
Definition at line 876 of file Socket.hpp.
is_tcp_no_delay() [2/2]
bool toolbox::net::Sock::is_tcp_no_delay () const inline
Definition at line 880 of file Socket.hpp.
close()
void toolbox::net::Sock::close () inline
Definition at line 881 of file Socket.hpp.
set_non_block() [1/2]
void toolbox::net::Sock::set_non_block (std::error_code & ec) inline noexcept
Definition at line 883 of file Socket.hpp.
Referenced by toolbox::net::StreamConnector< DerivedT >::connect().
set_non_block() [2/2]
void toolbox::net::Sock::set_non_block () inline
Definition at line 884 of file Socket.hpp.
set_rcv_buf() [1/2]
void toolbox::net::Sock::set_rcv_buf (int size, std::error_code & ec) inline noexcept
Definition at line 886 of file Socket.hpp.
set_rcv_buf() [2/2]
void toolbox::net::Sock::set_rcv_buf (int size) inline
Definition at line 890 of file Socket.hpp.
set_reuse_addr() [1/2]
void toolbox::net::Sock::set_reuse_addr (bool enabled, std::error_code & ec) inline noexcept
Definition at line 892 of file Socket.hpp.
Referenced by toolbox::net::StreamAcceptor< DerivedT >::StreamAcceptor().
set_reuse_addr() [2/2]
void toolbox::net::Sock::set_reuse_addr (bool enabled) inline
Definition at line 896 of file Socket.hpp.
set_snd_buf() [1/2]
void toolbox::net::Sock::set_snd_buf (int size, std::error_code & ec) inline noexcept
Definition at line 898 of file Socket.hpp.
set_snd_buf() [2/2]
void toolbox::net::Sock::set_snd_buf (int size) inline
Definition at line 902 of file Socket.hpp.
enable_hardware_rcv_timestamps() [1/2]
void toolbox::net::Sock::enable_hardware_rcv_timestamps () inline
Definition at line 904 of file Socket.hpp.
enable_hardware_rcv_timestamps() [2/2]
void toolbox::net::Sock::enable_hardware_rcv_timestamps (std::error_code & ec) inline noexcept
Definition at line 911 of file Socket.hpp.
disable_hardware_rcv_timestamps() [1/2]
void toolbox::net::Sock::disable_hardware_rcv_timestamps () inline
Definition at line 919 of file Socket.hpp.
disable_hardware_rcv_timestamps() [2/2]
void toolbox::net::Sock::disable_hardware_rcv_timestamps (std::error_code & ec) inline noexcept
Definition at line 929 of file Socket.hpp.
The documentation for this struct was generated from the following file:
toolbox/net/Socket.hpp